#!/usr/bin/env python3
"""Export one MIDAS JSONL trace as a normalized C feature window."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

def find_root() -> Path:
    here = Path(__file__).resolve()
    for parent in [here.parent, *here.parents]:
        if (parent / "models" / "midas_hybrid_rnn.npz").exists():
            return parent
    return here.parents[2]


ROOT = find_root()
for item in [ROOT / "src", ROOT]:
    if str(item) not in sys.path:
        sys.path.insert(0, str(item))

from midas import NumpyHybridRNNClassifier, read_jsonl, EwmaCusumDetector, DetectorConfig, summarize_window  # noqa: E402


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", required=True)
    parser.add_argument("--trace", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    classifier = NumpyHybridRNNClassifier(Path(args.model))
    detector = EwmaCusumDetector(DetectorConfig())
    detections = [detector.process(r) for r in read_jsonl(Path(args.trace))]
    summary = summarize_window(Path(args.trace), None, detections)
    raw = classifier._build_sequence([d.record for d in detections])
    x = ((raw - classifier.mean) / classifier.std).astype(np.float32)
    cls = classifier.classify([d.record for d in detections], summary)

    flat = x.reshape(-1)
    values = ", ".join(f"{v:.9g}f" for v in flat)
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "/* Auto-generated by export_trace_to_c.py. */\n"
        "#ifndef MIDAS_RNN_INPUT_H\n#define MIDAS_RNN_INPUT_H\n\n"
        f"#define MIDAS_EXPECTED_CLASS {cls}\n"
        f"static const float midas_input_window[{flat.size}] = {{ {values} }};\n\n"
        "#endif\n",
        encoding="ascii",
    )
    print(f"wrote {out} expected_class={cls}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
