#!/usr/bin/env python3
"""Export the MIDAS numpy/PyTorch weight archive as a C header."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np


def emit_array(name: str, arr: np.ndarray) -> str:
    flat = arr.astype(np.float32).reshape(-1)
    values = ", ".join(f"{x:.9g}f" for x in flat)
    return f"static const float {name}[{flat.size}] = {{ {values} }};\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    weights = np.load(args.model)
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)

    feature_dim = int(weights["feature_mean"].shape[0])
    hidden_dim = int(weights["lstm__weight_hh_l0"].shape[1])
    timesteps = int(weights["timesteps"][0])
    classes = int(weights["fc__bias"].shape[0])

    parts = [
        "/* Auto-generated by export_rnn_to_c.py. */\n",
        "#ifndef MIDAS_RNN_WEIGHTS_H\n#define MIDAS_RNN_WEIGHTS_H\n\n",
        f"#define MIDAS_FEATURE_DIM {feature_dim}\n",
        f"#define MIDAS_HIDDEN_DIM {hidden_dim}\n",
        f"#define MIDAS_TIMESTEPS {timesteps}\n",
        f"#define MIDAS_CLASSES {classes}\n\n",
    ]
    for key in [
        "feature_mean",
        "feature_std",
        "lstm__weight_ih_l0",
        "lstm__weight_hh_l0",
        "lstm__bias_ih_l0",
        "lstm__bias_hh_l0",
        "gru__weight_ih_l0",
        "gru__weight_hh_l0",
        "gru__bias_ih_l0",
        "gru__bias_hh_l0",
        "fc__weight",
        "fc__bias",
    ]:
        parts.append(emit_array("midas_" + key.replace("__", "_"), weights[key]))
    parts.append("\n#endif\n")
    out.write_text("".join(parts), encoding="ascii")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
